#!/bin/bash
echo "================================================"
sqlite3 ../databases/oiuc.db << HERE | awk '
{ 
    for (i=1; i<=NF; i++)  {
        a[NR,i] = $i
    }
}
NF>p { p = NF }
END {    
    for(j=1; j<=p; j++) {
        str=a[1,j]
        for(i=2; i<=NR; i++){
            str=str":\t\t"a[i,j];
        }
        print str
    }
}'
.mode list
.header on
.separator " "
select * from ics_config;
HERE
echo "================================================"
